178771330_gateway_errors
firstmoversadvantage/fmadata_parse_name pull request #5
Opened 2021-07-28 12:09 UTC by psuchta

- Title
  Suppress gateway errors
- Pivotal Link
https://www.pivotaltracker.com/story/show/178771330
- Tests
 Run tests to see if they pass

2021-07-30 11:08 UTC, radek-polcode requested changes

2021-07-30 11:08 UTC, radek-polcode commented on lib/fmadata_parse_name/v2/client.rb
> +        if [502, 504].include? e.response.code
Try to raise these errors similar to line 27 and then rescue them in the apps.

2021-08-03 14:32 UTC, radek-polcode approved these changes

2021-08-03 14:32 UTC, radek-polcode commented on lib/fmadata_parse_name/v2/client.rb
> +          retries = (retries || 1) + 1
```suggestion
          retries = (retries || 0) + 1
          sleep(1) && retry if retries < 3
```

2021-08-04 09:19 UTC, kbiala approved these changes

2021-08-23 21:43 UTC, merged